spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - SaveSession
          routes:
            - id: nextjs
              uri: ${UI_HOST:http://storefront-nextjs:3000}
              order: 100
              predicates:
                - Path=/**